apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-loki
  namespace: loki
  labels:
    app: loki
    chart: loki-2.9.1
    release: loki
    heritage: Helm
data:
  loki.yaml: |
    auth_enabled: false
    chunk_store_config:
      max_look_back_period: 0s
    compactor:
      shared_store: aws
      working_directory: /data/loki/boltdb-shipper-compactor
    ingester:
      chunk_block_size: 262144
      chunk_idle_period: 3m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      max_transfer_retries: 0
      wal:
        dir: /data/loki/wal
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    schema_config:
      configs:
      - from: "2022-01-01"
        index:
          period: 0
          prefix: index_
        object_store: aws
        schema: v11
        store: aws
    server:
      http_listen_port: 3100
    storage_config:
      aws:
        s3: s3://LOKI_STORE_REGION/LOKI_BUCKET_NAME
        dynamodb:
          dynamodb_url: dynamodb://LOKI_STORE_REGION
    table_manager:
      retention_deletes_enabled: true
      retention_period: 720h
      index_tables_provisioning:
        enable_ondemand_throughput_mode: true